apiVersion: v1
kind: ServiceAccount
metadata:
  name: hibernate-manager
  namespace: hibernate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hibernate-manager-role
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group, "apps" indicate "AppsV1"
  resources: ["deployments", "statefulsets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hibernate-manager-role-binding
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: hibernate-manager
  namespace: hibernate
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole # this must be Role or ClusterRole
  name: hibernate-manager-role
  apiGroup: rbac.authorization.k8s.io
